default['opentsdb']['ifcfg'] = 'lo'
default['opentsdb']['user'] = 'root'
default['opentsdb']['hbase_rootdir'] = '/tmp/tsdhbase'
default['opentsdb']['hbase_installdir'] = '/usr/local'
default['opentsdb']['hbase_version'] = '0.92.1'
default['opentsdb']['tgz_rootdir'] = '/tmp/tgz'
default['opentsdb']['opentsdb_installdir'] = '/usr/local'
default['opentsdb']['tsd_tmpdir']='/tmp/tsd'
default['opentsdb']['build_from_src'] = true
default['opentsdb']['create_opentsdb_tables'] = true
